version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules
  docker-react-app:
    build: ./docker-react-app
    container_name: docker-react-app_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    # volumes:
    #   - ./docker-react-app:/app
    #   - ./app/node_modules
